### ISSUE TITLE
screencast OOM error

### ISSUE THREAD

**Issue by rajeeshknambiar** [dbermond/screencast#13]
Tried to run screencast (with and without VAAPI); after a few seconds the system is slow to respond and in a couple of minutes screencast errors out. System log reports OOM error.

Here's what I do:
```
screencast -u -s 3200x1800 -v h264_vaapi
```
which spawns `ffmpeg` with following options:
```
ffmpeg -f alsa -thread_queue_size 3096 -sample_rate 48000 -channels 2 -channel_layout stereo -i default -f x11grab -thread_queue_size 3096 -probesize 20M -show_region 1 -region_border 2 -framerate 25 -video_size 3200x1800 -i :0.0+0,0 -vf fps=25 -codec:a pcm_s16le -ar 48000 -ac 2 -codec:v ffv1 -level 3 -slicecrc 1 -movflags +faststart -metadata comment=Created with screencast v1.5.0.next https://github.com/dbermond/screencast/ -y /home/rajeesh/.screencast/tmp.seBqaC/screencast-lossless-3849-bBXxqEQXvSJiMwW8pYWP.mkv
```

which spews out:
```
screencast v1.5.0.next - Copyright (c) 2015-2020 Daniel Bermond
Command line interface to record a X11 desktop
https://github.com/dbermond/screencast/
[ screencast ] initializing
[ screencast ] video encoder   : x264 (default)
[ screencast ] audio encoder   : aac (default)
[ screencast ] container format: mp4 (default)
[ screencast ] effects         : none
[ screencast ] recording
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, alsa, from 'default':
  Duration: N/A, start: 1599883739.713055, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[x11grab @ 0x55e7498a5500] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #1, x11grab, from ':0.0+0,0':
  Duration: N/A, start: 1599883739.760099, bitrate: N/A
    Stream #1:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 3200x1800, 25 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #1:0 -> #0:0 (rawvideo (native) -> ffv1 (native))
  Stream #0:0 -> #0:1 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, matroska, to '/home/rajeesh/.screencast/tmp.LjBlSv/screencast-lossless-4204-PDtzffdlUE5ljDGMVzV6.mkv':
  Metadata:
    comment         : Created with screencast v1.5.0.next
                    : https://github.com/dbermond/screencast/
    encoder         : Lavf58.29.100
    Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), bgr0, 3200x1800, q=2-31, 200 kb/s, 25 fps, 1k tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.54.100 ffv1
    Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
    Metadata:
      encoder         : Lavc58.54.100 pcm_s16le
[alsa @ 0x55e74988ae40] Thread message queue blocking; consider raising the thread_queue_size option (current value: 3096)
[matroska @ 0x55e7498b15c0] Non-monotonous DTS in output stream 0:1; previous: 25414, current: 25374; changing to 25414. This may result in incorrect timestamps in the output file.
[matroska @ 0x55e7498b15c0] Non-monotonous DTS in output stream 0:1; previous: 25414, current: 25377; changing to 25414. This may result in incorrect timestamps in the output file.
[matroska @ 0x55e7498b15c0] Non-monotonous DTS in output stream 0:1; previous: 25414, current: 25381; changing to 25414. This may result in incorrect timestamps in the output file.
[matroska @ 0x55e7498b15c0] Non-monotonous DTS in output stream 0:1; previous: 25414, current: 25384; changing to 25414. This may result in incorrect timestamps in the output file.
```

And once crashed, `journalctl` output shows OOM error:
```
Sep 12 09:37:23 athena kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/apps-konsole-98ffaf64ed5b4c8fa8d364fce27ab4c4.scope,task=ffmpeg,pid=4042,uid=1000
Sep 12 09:37:23 athena kernel: Out of memory: Killed process 4042 (ffmpeg) total-vm:13614968kB, anon-rss:7224868kB, file-rss:0kB, shmem-rss:26728kB, UID:1000 pgtables:18512kB oom_score_adj:0
Sep 12 09:37:23 athena kernel: oom_reaper: reaped process 4042 (ffmpeg), now anon-rss:0kB, file-rss:0kB, shmem-rss:26728kB
Sep 12 09:37:23 athena systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
```

Please let me know if you need additional information.

**Comment by dbermond** [comment]
What is your operating system?

Does the same error occur when running the direct ffmpeg command? (don't forget to enclose in quotes the contents of `comment=`)

**Comment by rajeeshknambiar** [comment]
> What is your operating system?

GNU/Linux, Fedora 32, x86_64, kernel 5.7.17, Intel i7-6500U, Intel HD Graphics 520 (SKL GT2).

> 
> Does the same error occur when running the direct ffmpeg command? (don't forget to enclose in quotes the contents of `comment=`)

Yes, it does OOM when I run `ffmpeg` directly with those options.

But, I have been running ffmpeg directly without issues. For instance, I can use this 1-pass recording of screen, webcam and audio, with no system lag or OOM:
```
"ffmpeg -f alsa -i pulse -f x11grab -vaapi_device /dev/dri/renderD128  -video_size 3200x1800 -framerate 30 -i :0 -f v4l2 -thread_queue_size 64 -video_size 240x150 -framerate 30 -i /dev/video0 -filter_complex 'overlay=main_w-overlay_w-10:10:format=yuv444,format=nv12|vaapi,hwupload' -vcodec h264_vaapi -preset ultrafast -qp 24 -pix_fmt yuv444p video.mkv"
```

**Comment by dbermond** [comment]
> Yes, it does OOM when I run ffmpeg directly with those options.

Then it looks like this is not a screencast bug. You're having a low-memory problem in running ffmpeg and I cannot help you much further with this.

> But, I have been running ffmpeg directly without issues. For instance, I can use this 1-pass recording of screen, webcam and audio, with no system lag or OOM:
> 
> "ffmpeg -f alsa -i pulse -f x11grab -vaapi_device /dev/dri/renderD128  -video_size 3200x1800 -framerate 30 -i :0 -f v4l2 -thread_queue_size 64 -video_size 240x150 -framerate 30 -i /dev/video0 -filter_complex 'overlay=main_w-overlay_w-10:10:format=yuv444,format=nv12|vaapi,hwupload' -vcodec h264_vaapi -preset ultrafast -qp 24 -pix_fmt yuv444p video.mkv"

This command encodes the video stream to H.264. But you're having problem in recording the lossless video with ffv1 and pcm_s16le codecs, so it seems different. In analogy, screencast should work for you if you use the `--one-step` option, since it will not record to a lossless video.

Make sure that you have a good amount of RAM (I suppose you have) and/or swapspace. Also, try to use the most up-to-date ffmpeg version, which currently is 4.3.1, or even the git master version (it's quite stable). They usually fix buffer related bugs between releases, so it may be worth to try. If you need to compile, see instructions on the [ffmpeg compilation guide](https://trac.ffmpeg.org/wiki/CompilationGuide/).

If the error persists on running the direct ffmpeg command to record a lossless video, my suggestion is that you seek help in other channels, like your operating system support channels or even at some ffmpeg support channel.

**Comment by rajeeshknambiar** [comment]
> > Yes, it does OOM when I run ffmpeg directly with those options.
> 
> Then it looks like this is not a screencast bug. You're having a low-memory problem in running ffmpeg and I cannot help you much further with this.

Ok.

> This command encodes the video stream to H.264. But you're having problem in recording the lossless video with ffv1 and pcm_s16le codecs, so it seems different. In analogy, screencast should work for you if you use the `--one-step` option, since it will not record to a lossless video.

I did try the one-step option too, but that was OOM killed as well. Here is the command used and its corresponding `ffmpeg`:
```
screencast -s 3200x1800 -r 30 -f mkv -u -v h264_vaapi -W -Z 120x90 -R 45 -1

ffmpeg -f alsa -thread_queue_size 3096 -sample_rate 48000 -channels 2 -channel_layout stereo -i default -vaapi_device /dev/dri/renderD128 -f x11grab -thread_queue_size 3096 -probesize 20M -show_region 1 -region_border 2 -framerate 30 -video_size 3200x1800 -i :0.0+0,0 -f video4linux2 -thread_queue_size 3096 -probesize 10M -framerate 45 -video_size 120x90 -i /dev/video0 -filter_complex overlay=main_w-overlay_w-10:10,format=bgr0,fps=30,format=nv12,hwupload -codec:a aac -b:a 128k -ar 44100 -ac 2 -codec:v h264_vaapi -qp 18 -pix_fmt vaapi_vld -metadata comment="Created with screencast v1.5.0.next https://github.com/dbermond/screencast/" -y /home/rajeesh/screencast-2020-09-13_09.39.30.mkv
```

> If the error persists on running the direct ffmpeg command to record a lossless video, my suggestion is that you seek help in other channels, like your operating system support channels or even at some ffmpeg support channel.

Ok, thanks.

**Comment by dbermond** [comment]
Have you tried to use smaller resolutions? Omit the `-s` option for using the default 640x480 resolution.

Have you tried to disable audio with `-i none`?

**Comment by rajeeshknambiar** [comment]
> Have you tried to use smaller resolutions? Omit the `-s` option for using the default 640x480 resolution.

Works fine with default resolution. I can see the memory usage is consistently at 1.2%–1.3% range. But with larger or full resolution, memory usage starts around 42% and quickly saturates resulting in OOM.
 
> Have you tried to disable audio with `-i none`?

No difference with `-i none` option (meaning large resolution is still OOM).

**Comment by dbermond** [comment]
Would you mind informing the amount of ram that you have?

**Comment by dbermond** [comment]
Try to modify `queue_size='3096'` in `src/settings_general.sh` (line 31) to a smaller value like 32, 64, 128, etc.

I think this will avoid your issue but at the other hand you probably will have some packet loss.

**Comment by rajeeshknambiar** [comment]
> Try to modify `queue_size='3096'` in `src/settings_general.sh` (line 31) to a smaller value like 32, 64, 128, etc.

That indeed have an effect. Setting `queue_size` to 128 limited RAM usage to 50% (8 GB RAM); while the value 32 using under 23% of RAM in two-pass. RAM usage is even lower (also the fan noise) in 1-pass (around 12% with `queue_size = 32`) but increased file size (understandably).

> I think this will avoid your issue but at the other hand you probably will have some packet loss.

But, yes — the video is not recorded in full length. It seems not to contain final few seconds of the few minutes recorded for testing.

**Comment by dbermond** [comment]
So, it looks like we have found what's hapenning.

In short: it seems that your hardware do not have enough processing power to record video with a huge resolution like 3200x1800. At least not in the way how screencast works.

The long story:

When reading input files (as we are reading from the input devices), [_"packets may be discarded if they are not read in a timely manner"_](https://github.com/FFmpeg/FFmpeg/blob/n4.3.1/doc/ffmpeg.texi#L1681-L1685) by ffmpeg. This means that if the CPU/GPU cannot process the input data fastly enough, input packets will be discarded by ffmpeg. That's why ffmpeg shows the warning _"Thread message queue blocking; consider raising the thread_queue_size option"_, meaning that packets are being discarded (ffmpeg is already giving you this message in the log of your very first post). As you can see, ffmpeg is also pointing the solution: raise the `thread_queue_size` option, which defaults to 8 (a low value for the needs of input devices). This is a per-input option, and being such, it's a good practice to set it for every input device (alsa, x11grab, webcam, watermark, etc), otherwise you may be risking to lose precious packets from the input streams.

Taking this in consideration, screencast sets a `thread_queue_size` value that's high enough to make all the input data not to be discarded, or at least tries to do so. I experimented a lot to reach a good value for this option. Some people report to use 512, other 1024. But in my tests, this was not enough and always gave me the _"Thread message queue blocking"_ warning in at least one input device when recording in a long run. Yes, a value of 3096 probably is a bit high (3 times higher than 1024 which some people use), but this was never a problem for me, as long as having the needed processing power for what you're wanting to record.

Among all the inputs used by screencast, the most resource hungry is the video stream taken from the x11grab device. The higher the video resolution, the greater the processing power required. And recording a very high resolution like 3200x1800 requires **a lot** of processing power. As you could see in the tests that I have asked you to do, you were able record fine with lower resolutions, because it requires less processing power. And when you use a huge resolution like 3200x1800, you reach a hardware bottleneck that causes a system crash/OOM. By looking at your [Core i7-6500U CPU specifications](https://ark.intel.com/content/www/us/en/ark/products/88194/intel-core-i7-6500u-processor-4m-cache-up-to-3-10-ghz.html), we can see that it's a dual core, with an integrated graphics chip of 300MHz base clock for VAAPI. I personally think that a dual core CPU is not sufficient for recording a 3200x1800 video.

Lowering the `thread_queue_size` to something like 32, 64 or 128 worked for you at the cost of having packet loss, and this is not the desire here in screencast. As I have explained above, I have tried to reach a good value for having no packet loss, or at least the less possible packet loss. But, depending on the video resolution, this will require a greater processing power. For example, I can record a 1920x1200 video in a long run without any issues.

You may argue that you have a [manual ffmpeg command](https://github.com/dbermond/screencast/issues/13#issuecomment-691476399) to record x11grab + webcam + alsa that works for you, but in your example you have used `thread_queue_size` only for the webcam input (which requires not that high processing power) and with a very low value of 64. This probably means that you have some packet loss in some input stream when recording a 3200x1800 Xorg resolution and/or that you're risking to lose packets from the x11grab and alsa devices, since the default value of 8 that is being used for them is too low for input devices.

Solution for you on screencast: set a lower resolution or use hardware with sufficient processing power for the desired resolution.

**Comment by rajeeshknambiar** [comment]
Thanks a lot for the analysis and detailed explanation!

That said, I’ll probably resort to the manual ffmpeg command and check if there are significant packet losses in screen/audio as suggested.

BTW, I have packaged the master branch of screencast for Fedora/CentOS and made available here: https://copr.fedorainfracloud.org/coprs/rajeeshknambiar/screencast/
